name: release

on:
  push:
    tags:
      - 'v*'

env:
  NOTES: "/tmp/notes.md"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Download release notes utility
        env:
          GH_REL_URL: https://github.com/buchanae/github-release-notes/releases/download/0.2.0/github-release-notes-linux-amd64-0.2.0.tar.gz
        run: cd /tmp && curl -sSL "${GH_REL_URL}" | tar xz && sudo mv github-release-notes /usr/local/bin/

      - name: Generate release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## JSON Schema Generate" > "${NOTES}"
          github-release-notes -org awesomeengineers -repo json-schema-generate -since-latest-release >> "${NOTES}"

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: ${{ env.NOTES }}
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::"${GITHUB_REF/refs\/tags\//}"

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          tags: |
            ghcr.io/awesomeengineers/json-schema-generate:${{ steps.get_version.outputs.VERSION }}
